controller_list:
  - name: fake_l_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - l_joint1
      - l_joint2
      - l_joint3
      - l_joint4
      - l_joint5
      - l_joint6
      - l_joint7
  - name: fake_r_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - r_joint1
      - r_joint2
      - r_joint3
      - r_joint4
      - r_joint5
      - r_joint6
      - r_joint7
  - name: fake_l_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - l_Joint_finger1
  - name: fake_r_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r_Joint_finger1
initial:  # Define initial robot poses per group
  - group: l_arm
    pose: home
  - group: r_arm
    pose: home
  - group: l_gripper
    pose: open
  - group: r_gripper
    pose: open